// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsTask.Database;

namespace WinFormsTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230827125741_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WinFormsTask.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyIIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyIIN = "284017482912",
                            CompanyName = "Microsoft",
                            PhysicalAddress = "5331 Rexford Court, Montgomery AL 36116",
                            Remark = "Американская публичная транснациональная корпорация, один из крупнейших разработчиков в сфере проприетарного программного обеспечения для различного рода вычислительной техники."
                        },
                        new
                        {
                            Id = 2,
                            CompanyIIN = "5930285930581",
                            CompanyName = "Google",
                            PhysicalAddress = "8642 Yule Street, Arvada CO 80007",
                            Remark = "Американская многонациональная технологическая компания, специализирующаяся на искусственном интеллекте, онлайн-рекламе, технологиях поисковых систем, облачных вычислениях, компьютерном программном обеспечении."
                        },
                        new
                        {
                            Id = 3,
                            CompanyIIN = "918294757382",
                            CompanyName = "Nissan",
                            PhysicalAddress = "4001 Anderson Road, Nashville TN 37217",
                            Remark = "Японский автопроизводитель, один из крупнейших в мире."
                        },
                        new
                        {
                            Id = 4,
                            CompanyIIN = "283749104738",
                            CompanyName = "Shell",
                            PhysicalAddress = "2436 Naples Avenue, Panama City FL 32405",
                            Remark = " Британско-нидерландская нефтегазовая компания."
                        },
                        new
                        {
                            Id = 5,
                            CompanyIIN = "728394719472",
                            CompanyName = "Siemens",
                            PhysicalAddress = "19141 Pine Ridge Circle, Anchorage AK 99516",
                            Remark = "Немецкий конгломерат, работающий в области электротехники, электроники, энергетического оборудования"
                        });
                });

            modelBuilder.Entity("WinFormsTask.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            EmployeeIIN = "981224472838",
                            FirstName = "Алексей",
                            Patronymic = "Вавилович",
                            Surname = "Иванов"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            EmployeeIIN = "870312372849",
                            FirstName = "Артём",
                            Patronymic = "Геннадиевич",
                            Surname = "Смирнов"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            EmployeeIIN = "990807299374",
                            FirstName = "Вадим",
                            Patronymic = "Данилович",
                            Surname = "Кузнецов"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            EmployeeIIN = "011119948293",
                            FirstName = "Владимир",
                            Patronymic = "Егорович",
                            Surname = "Попов"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            EmployeeIIN = "780413243656",
                            FirstName = "Валентин",
                            Patronymic = "Игоревич",
                            Surname = "Васильев"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            EmployeeIIN = "890829574829",
                            FirstName = "Данил",
                            Patronymic = "Карлович",
                            Surname = "Петров"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 2,
                            EmployeeIIN = "900523673927",
                            FirstName = "Денис",
                            Patronymic = "Леонидович",
                            Surname = "Соколов"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            EmployeeIIN = "860917574839",
                            FirstName = "Дмитрий",
                            Patronymic = "Макарович",
                            Surname = "Михайлов"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 4,
                            EmployeeIIN = "950722374860",
                            FirstName = "Егор",
                            Patronymic = "Маркович",
                            Surname = "Николаев"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 5,
                            EmployeeIIN = "791228473829",
                            FirstName = "Кирилл",
                            Patronymic = "Нефёдович",
                            Surname = "Крылов"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 1,
                            EmployeeIIN = "030208564738",
                            FirstName = "Леонид",
                            Patronymic = "Николаевич",
                            Surname = "Максимов"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 2,
                            EmployeeIIN = "991023574839",
                            FirstName = "Максим",
                            Patronymic = "Олегович",
                            Surname = "Сидоров"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 3,
                            EmployeeIIN = "880730564738",
                            FirstName = "Матвей",
                            Patronymic = "Павлович",
                            Surname = "Осипов"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 4,
                            EmployeeIIN = "810524674839",
                            FirstName = "Никита",
                            Patronymic = "Петрович",
                            Surname = "Белоусов"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 5,
                            EmployeeIIN = "020426576348",
                            FirstName = "Олег",
                            Patronymic = "Робертович",
                            Surname = "Федотов"
                        });
                });

            modelBuilder.Entity("WinFormsTask.Models.Employee", b =>
                {
                    b.HasOne("WinFormsTask.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
